SET(MODULE_NAME "print-module")

GET_FILENAME_COMPONENT(PROJ_ROOT "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)

SET(PRINT_MODULE_ROOT ${PROJ_ROOT}/print-iotjs/print/)
SET(PRINT_MODULE_JS_FILE ${PROJ_ROOT}/print-iotjs/print/print-module.js)

SET(CMAKE_VERBOSE_MAKEFILE ON)

INCLUDE_DIRECTORIES("${PRINT_MODULE_ROOT}")

ADD_COMPILE_OPTIONS("-DPRINT_MODULE_JS_FILE=\"${PRINT_MODULE_JS_FILE}\"")
